### ISSUE TITLE
RELEASE v4

### ISSUE THREAD

**Issue by Anush008** [Anush008/fastembed-rs#110]
Dear @triandco, @denwong47 and @lywa1998.

I am considering running the [release action](https://github.com/Anush008/fastembed-rs/actions/workflows/release.yml) on the weekend which will release v4.

Will do some Q&A tests till then to check usability and look for any improvements.

Thanks again for taking the time to contribute.

**Comment by denwong47** [comment]
No worries, let us know if you encounter any issues.

Now that I understand the modules better there are certain changes I would like to propose to bring `text` and `sparse text` in line (e.g. make `text` use `post_process` like `sparse`), but the changes should not be breaking, so that can come later.

**Comment by Anush008** [comment]
Will be adding https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute to the options structs and introduce a builder pattern.

We can then introduce more options if needed without breaking.
